name: "node-redciaq"
services:
  script:
    build: ./app/
    container_name: script
    depends_on:
      - weewx
    networks:
      - node-network
  weewx:
    image: instantlinux/weewx:5.1.0
    container_name: weewx
    networks:
      - node-network
networks:
  node-network:
    driver: bridge
